### PR TITLE
Implement of UpdateManager 2.1 (I hope Final Version....)

### PR DESCRIPTION
**Pull request by LightDestory**
UpdateManager 2.1:
- Now Supports 32bit and 64bit
- Fixed No-Network Available Start (I totaly missed this XD I have Network always available)
- Colors on Console! (Just to make it more colorfull and not black-white)

General Info:
- VSCodePortable.exe runs UpdateManager that will check for update, if found apply it, and then start VSCode. The launch of 32bit or 64bit version is managed by UpdateManager, so I removed the "ProgrammExecutable64" flag from Launcher.ini and added the 'WaitForExe" flag.
- The Downalod-Apply of Update is totally automated!
- UpdateManager will update both versions (32bit and 64bit), so it will take more time then before...
- When found a Update the approx. download size is: 180MB (32bit.zip + 64bit.zip)
- Source code is always available on my repo
- If you need help contact me!

### CODE REVIEW

**Comment by arkadycc** [comment]
Hi,
awesome... but can you please fix the path length (>260) issue und merge it?
Thanks a lot (in advance)
Andreas

**Comment by LightDestory** [comment]
The >260 limit is OS based. So I can't resolve it in a "portable way".
BTW this tool is used on a "already download software" so if you have already installed once you will not get the issue anymore.
I can't merge it. I am not the owner of repo

**Comment by arkadycc** [comment]
Thanks a lot for all your afford!
It saved me a headache and a view hours ;-)

**Comment by arkadycc** [comment]
Simple Test worked fine... thanks a lot... nicely done

**Pull request closed without merging**
